Map<String, String> getLista() {
  return {
    '1': 'Tião',
    '3': 'Fabi do Fabio',
    '4': 'Diego da Julliana',
    '7': 'Eliane Pós',
    '8': 'Cecília BA',
    '9': 'Vivi do Edgar',
    '10': 'Maria de Fátima',
    '11': 'Izamara Emir',
    '12': 'Erika da Sarinha',
    '14': 'Luciana Emir',
    '15': 'Lau Emir',
    '16': 'Mayara do João',
    '18': 'Jana do Daniel',
    '19': 'Fran do Elizete',
    '20': 'Tamires do Erick',
    '21': 'Lau do Emir',
    '22': 'Zoraide',
    '24': 'Rozi do Thiago',
    '26': 'Silvana da Calçada',
    '27': 'Marcilene do Emir',
    '29': 'Maurício da Aldenice',
    '30': 'Marcelo BA',
    '31': 'Cris Harmonia',
    '32': 'Marluce',
    '33': 'Vagner da Mônica',
    '34': 'Carlos da Viviane',
    '35': 'Gisele Mãe do Luan',
    '36': 'Shirley do Lucas',
    '37': 'Mônica do Vagner',
    '38': 'Suzana do Romildo',
    '39': 'Andreia do Andrei',
    '40': 'Marluce',
    '41': 'Ju do Narcizo',
    '42': 'Daniel da Jana',
    '43': 'Fatima Pão',
    '44': 'Hilton BA',
    '45': 'Ju do Narcizo',
    '46': 'Rosilene Emir',
    '47': 'Meire do William',
    '48': 'Maya',
    '49': 'Elizete Mãe do Arthur',
    '51': 'Vander BA',
    '52': 'Adilson',
    '53': 'Ricardo Emir',
    '55': 'Lúcia do Paulo',
    '56': 'Viviane do Carlos',
    '57': 'Rodrigo Takedomi',
    '58': 'Sirene Emir',
    '59': 'Miriam Emir',
    '60': 'Walkiria do Douglas',
    '61': 'Fernando do Théozinho',
    '62': 'Alana',
    '63': 'Paulo Enio Serpro',
    '64': 'Joelma do Jairo',
    '65': 'Maura',
    '67': 'José Fidelis',
    '68': 'Paulo Enio Serpro',
    '69': 'Dona Graça BA',
    '70': 'Anderson da Marcia',
    '72': 'Cirlene Fiuza',
    '73': 'Claudia do Paulo',
    '75': 'Jaque do Jackson',
    '76': 'Marcos André Serpro',
    '77': 'Walkiria do Douglas',
    '78': 'Eliane do Elder',
    '79': 'Marcos André Serpro',
    '80': 'Paula do Renato',
    '81': 'Fernando prof Natação',
    '82': 'Fernando prof Natação',
    '83': 'Jam',
    '84': 'Margareth',
    '85': 'Valeria Vizinha',
    '86': 'Cecília do Edemir',
    '88': 'Verinha do Wilson',
    '90': 'Julliana do Diego',
    '91': 'Cris do Franklyn',
    '92': 'Gisele do Emir',
    '94': 'Anderson da Marcia',
    '98': 'Renata do Lucio',
    '99': 'Vander BA',
    '100': 'Eliane do Anderson',
    '105': 'Anderson da Marcia',
    '107': 'José Fidelis',
    '109': 'Alaide Emir',
    '111': 'Walkiria do Douglas',
    '115': 'Claudete',
    '116': 'Sueli do Fiuza',
    '117': 'Marcelo da Gislene',
    '119': 'Renata do Lucio',
    '120': 'Walkiria do Douglas',
  };
}
